apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-argocd-helm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
