service:
  type: ClusterIP
  port: 80

container:
  port: 8080

resources:
  requests:
    memory: 1Gi
    cpu: 512m
  limits:
    memory: 2Gi
    cpu: 1

environments:
  - name: APP_ENV
    value: "dev"

image:
  repository: josabor/static-website-by-nginx
  tag: "main"
  pullPolicy: IfNotPresent
